### ISSUE TITLE
Add collaborators

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/lingrbot-means#15]
I'd be happy to add @aycabta , @raa0121 and others to collaborators, but I think some works should be done **before** that.

- Unit test using RSpec, and auto deploy (ref. #16)
- throw heroku away (ref. #14 )

And I think pull request based development is good way to keep product quality, even if all collaborators can push to master branch without review.

**Comment by aycabta** [comment]
OK, I'll write RSpec now.

**Comment by supermomonga** [comment]
Thanks. I'm working on #14.

**Comment by raa0121** [comment]
I can't write RSpec now...
I'll study it...

**Comment by supermomonga** [comment]
It's ok, basically those are my job. just helps be grateful.

**Comment by supermomonga** [comment]
Thanks @aycabta for adding tests. I added you two to the collaborators.
