### ISSUE TITLE
Missing lingr icon

### ISSUE THREAD

**Issue by ujihisa** [supermomonga/lingrbot-means#19]
![](https://gyazo.com/5f846b6b670205806ea1681333e70e78.png)

不便

**Comment by supermomonga** [comment]
これ、対策不能では感ある

**Comment by ujihisa** [comment]
うむ、で、これ実は対策できる人がただ一人存在します。

![](https://gyazo.com/b8e8319d43f82f72fa6f62f925174615.png)

> Master
> そうか、俺たちは…。そうだ、この未来永劫の時の狭間で戦うために。ここから先は俺達だけで十分だ。ケイ、おまえたちは。

なので、もしそうか、俺たちは…。そうだ、この未来永劫の時の狭間で戦うために。ここから先は俺達だけで十分だ。ケイ、おまえたちは。さんを見つけることができ、そうか、俺たちは…。そうだ、この未来永劫の時の狭間で戦うために。ここから先は俺達だけで十分だ。ケイ、おまえたちは。さんに本件を頼むことができれば、そうか、俺たちは…。そうだ、この未来永劫の時の狭間で戦うために。ここから先は俺達だけで十分だ。ケイ、おまえたちは。さんが解決してくれそうです。

**Comment by supermomonga** [comment]
一行が長いとはみ出して見えないってことだよね？

- ブラウザウィンドウの幅によって何文字ではみ出すか決定されるので、改行を挿入するような形では対応できない
- 元ツイートのニュアンスを変えてしまう場合があるのでできるだけ勝手に改行したくない

@ujihisa 何か案あれば。

**Comment by ujihisa** [comment]
意図力

lingrのアイコン (アバター?)が抜けているという意図でした(//

**Comment by supermomonga** [comment]
そっちか（なぜかタイトル見てなかった）

**Comment by ujihisa** [comment]
タイトル物理的に遠い位置に配置されてるので見るの実際むずかしい

**Comment by aycabta** [comment]
0721gomen1919
