### ISSUE TITLE
Test for twitter fails

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/lingrbot-means#20]
```
Failures:

  1) The Semantics=san twitter
     Failure/Error: post '/', create_message_json('https://twitter.com/kumikumitm/status/693000092534587392')

     Twitter::Error::Forbidden:
       Unable to verify your credentials
     # ./app.rb:246:in `twitter_content'
     # ./app.rb:128:in `handle_message'
     # ./app.rb:30:in `block (2 levels) in <class:Bot>'
     # ./app.rb:29:in `map'
     # ./app.rb:29:in `block in <class:Bot>'
     # ./spec/app_spec.rb:35:in `block (2 levels) in <top (required)>'
```

> Unable to verify your credentials

Can we set the option not to verify SSL certificate?

**Comment by aycabta** [comment]
Maybe, this error says ["give me access credentials; key and secret"](http://stackoverflow.com/questions/17719358/twittererrorforbidden-unable-to-verify-your-credentials). Old *thumb* bot was scraping web page, it was hard put to maintenance, so I think it's good to use Twitter API.

But, I have no idea for where will access credentials be written.

**Comment by aycabta** [comment]
I think, bearer token is best practice for this problem. I'll fix this issue with it.

**Comment by aycabta** [comment]
@supermomonga Please add this repository to Travis CI later.

**Comment by supermomonga** [comment]
ok I'll do it later
